# --------------
# -- Settings --
# --------------

title: Dr. Abdur R. Shad | Internal and Pulmonary Medicine | Denville, NJ
description: >-
  Board-certified physician serving Morris County with over 30 years of experience in Internal 
  and Pulmonary Medicine. Expert diagnosis and treatment of lung and airway diseases, 
  plus smoking-related conditions and cessation therapy.
  
baseurl: ""
url: "https://doctorabdurshad.github.io/"

# Compressed with TinyPNG
images:
  favicon: "/images/favicon.ico"
  profile: "/images/profile.png"
  nebulizer: "/images/nebulizer.png"
  telemedicine: "/images/telemedicine.png"
  consult: "/images/consultation.png"
  speaking: "/images/speaking.png"

# Build settings
theme: minima


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
