source "https://rubygems.org"

# Jekyll core for local site generation
gem "jekyll", "~> 4.3"

# Default theme
gem "minima", "~> 2.5"

# Feed plugin
gem "jekyll-feed", "~> 0.16"

# Required for Jekyll server on Ruby 3+
gem "webrick", "~> 1.8"

# Optional: Windows watcher (only for Windows)
platforms :mingw, :x64_mingw, :mswin do
  gem "wdm", "~> 0.2.0"
end
